name: Release

on:
  workflow_call:
    inputs:
      release_branch:
        description: 'The branch where push would trigger release workflow'
        default: 'main'
        required: true
        type: string

    outputs:
      released: 
        description: "Whether or not a release has been made"
        value: ${{ jobs.release.outputs.released }}

jobs:
  release:
    # If main branch is updated, we want to release the package.
    if: github.event_name == 'push' && github.ref == format('refs/heads/{0}', github.event.inputs.release_branch)
    concurrency: release
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    continue-on-error: true

    outputs:
      released: 
        value: ${{ steps.release.outputs.released }}

    steps:
      # Note: we need to checkout the repository at the workflow sha in case during the workflow
      # the branch was updated. To keep PSR working with the configured release branches,
      # we force a checkout of the desired release branch but at the workflow sha HEAD.
      - name: Setup | Checkout Repository at workflow sha
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user

      - name: Setup | Force correct release branch on workflow sha
        run: |
          git checkout -B ${{ github.ref_name }} ${{ github.sha }}

      - name: Action | Semantic Version Release
        id: release
        # Adjust tag with desired version if applicable.
        uses: python-semantic-release/python-semantic-release@v9.14.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          git_committer_name: "github-actions"
          git_committer_email: "actions@users.noreply.github.com"
          root_options: "--strict"

      - name: Build | Build the distribution packages
        run: >-
          python3 -m build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          path: dist/
          name: python-package-distributions

      - name: Publish | Upload to GitHub Release Assets
        uses: python-semantic-release/publish-action@v9.14.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.release.outputs.tag }}

