name: Release

on:
  workflow_call:
    inputs:
      release_branch:
        description: 'The branch where push would trigger release workflow'
        default: 'main'
        required: true
        type: string

    outputs:
      released: 
        description: "Whether or not a release has been made"
        value: ${{ jobs.release.outputs.released }}

    secrets:
      AUTO_RELEASE_PRIVATE_KEY:
        required: true

jobs:
  release:
    # If main branch is updated, we want to release the package.
    if: github.event_name == 'push' && github.ref == format('refs/heads/{0}', inputs.release_branch)
    concurrency: release
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write

    continue-on-error: true

    outputs:
      released: ${{ steps.release.outputs.released }}

    steps:
      - name: Setup | GitHub App Token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.AUTO_RELEASE_APP_ID }}
          private-key: ${{ secrets.AUTO_RELEASE_PRIVATE_KEY }}

      # Note: we need to check out the repository at the workflow sha in case during the workflow
      # the branch was updated. To keep PSR working with the configured release branches,
      # we force a checkout of the desired release branch but at the workflow sha HEAD.
      - name: Setup | Checkout Repository at workflow sha
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}
          token: ${{ steps.app-token.outputs.token }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install pypa/build
        run: >-
          python3 -m
          pip install
          build
          --user

      - name: Setup | Force correct release branch on workflow sha
        run: |
          git checkout -B ${{ github.ref_name }} ${{ github.sha }}

      - name: Action | Semantic Version Release
        id: release
        # Adjust tag with desired version if applicable.
        uses: python-semantic-release/python-semantic-release@1a324000f2251a9e722e77b128bf72712653813f  # v10.0.2
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          root_options: "--strict"

      - name: Build | Build the distribution packages
        run: >-
          python3 -m build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          path: dist/
          name: python-package-distributions

      - name: Publish | Upload to GitHub Release Assets
        uses: python-semantic-release/publish-action@1aa9f41fac5d531e6764e1991b536783337f3a56  # v9.21.1
        with:
          github_token: ${{ steps.app-token.outputs.token }}
          tag: ${{ steps.release.outputs.tag }}

