name: Tests and checks

on:
  workflow_call:
    inputs:
      project_name:
        description: 'The name of the project'
        required: true
        type: string
    secrets:
      CODECOV_TOKEN:
        required: true
      SONAR_TOKEN:
        required: true

jobs:
  tests:
    name: Run tests and checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t ${{ inputs.project_name }} .

      - name: Run tests
        run: |
          docker run --volume $(pwd):/app --workdir /app --rm ${{ inputs.project_name }} nox -s tests

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        with:
          args: >
            -Dsonar.organization=nextgencontributions
            -Dsonar.projectKey=django2pydantic
            -Dsonar.python.coverage.reportPaths=coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
