name: Auto upgrade trunk and its tools

on:
  workflow_call:
    secrets:
      BOT_PR_PRIVATE_KEY:
        required: true

# Define required permissions for the reusable workflow
permissions:
    contents: write # For trunk to create PRs
    pull-requests: write # For trunk to create PRs
    issues: write # For trunk to create labels

jobs:
  trunk_upgrade:
    name: Upgrade Trunk
    runs-on: ubuntu-latest
    steps:
      - name: Setup | GitHub App Token
        uses: actions/create-github-app-token@v3
        id: app-token
        with:
          app-id: ${{ vars.BOT_PR_APP_ID }}
          private-key: ${{ secrets.BOT_PR_PRIVATE_KEY }}
      
      - name: Checkout
        uses: actions/checkout@v7

      - name: Trunk Upgrade
        uses: trunk-io/trunk-action/upgrade@v2.0.0
        with:
          prefix: "chore(dev-tools): "
          labels: trunk
          # GitHub token to allow created PRs to run pull_request workflows
          github-token: ${{ steps.app-token.outputs.token }}
