name: Trunk check

on:
  workflow_call:
    inputs:
      check_mode:
        description: Trunk check-mode
        required: false
        type: string
      arguments:
        description: Trunk extra arguments
        required: false
        type: string
    secrets:
      TRUNK_TOKEN:
        required: true

jobs:
  trunk-code-quality:
    runs-on: ubuntu-latest
    permissions:
      checks: write # For trunk to post annotations
      contents: read # For repo checkout
    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7.1.2

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "pyproject.toml"

      - name: Install the project to system's python
        run: |
          UV_PROJECT_ENVIRONMENT=$pythonLocation \
          uv sync \
            --python=${{ env.pythonLocation }}/bin/python3 \
            --all-extras \
            --dev \
            --frozen \
            --no-install-project

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
        with:
          trunk-token: ${{ secrets.TRUNK_TOKEN }}
          check-mode: ${{ inputs.check_mode }}
          arguments: ${{ inputs.arguments }}
